/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.NhanVien;
import repository.NhanVienRepository;
import utils.Auth;
import utils.ImageHelper;
import utils.MsgBox;
import utils.TimeClockThread;

/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        init();  
    }

    void displayUserInfo() {
        NhanVienRepository re = new NhanVienRepository();
        Auth.user = re.selectById("TeoNV");
        
        String userID = Auth.user.getHoTen();
        String role = Auth.user.isVaiTro() ? "Quản lý" : "Nhân viên";
        lblInfo.setText("Người dùng: " + userID + " | " + "Vai trò: " + role);
    }

    private void init() {
        setLocationRelativeTo(null);
        this.setIconImage(ImageHelper.getAppIcon().getImage());
        TimeClockThread.startClock(lblTime);
        displayUserInfo();
    }

    void openChangePassword() {
        if (Auth.isLogin()) {
            new ChangePassJDialog(this, rootPaneCheckingEnabled).setVisible(true);
        }
    }

    void logOut() {
        Auth.clear();
        this.dispose();
        new DangNhapJFrame().setVisible(true);
    }
    
    void openThongKe(int index){
        new ThongKeJFrame().setVisible(true);
    }

    void exit() {
        if (MsgBox.confirm(this, "Thoát?")) {
            System.exit(0);
        }
    }

    void openChuyenDe() {
        new ChuyenDeJDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }

    void openKhoaHoc() {
        new KhoaHocJDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }

    void openNguoiHoc() {
        new NguoiHocJDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }

    void openHocVien() {
new HocVienJDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }

    void openNhanVien() {
new NhanVienJDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }

    void openGuide() {
        try {
            Desktop.getDesktop().browse(new URI("https://www.facebook.com/amitychu.vn"));
        } catch (IOException | URISyntaxException ex) {
            MsgBox.alert(this, "Không thấy file hướng dẫn");
        }
    }

    void openAbout(){
        new GioiThieuJDialog(this, rootPaneCheckingEnabled).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTime = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        btnLogout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnChuyenDe = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnGuide = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mbEduSYS = new javax.swing.JMenuBar();
        mHeThong = new javax.swing.JMenu();
        miChangPass = new javax.swing.JMenuItem();
        miLogout = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        mQuanLy = new javax.swing.JMenu();
        miChuyenDe = new javax.swing.JMenuItem();
        miKhoaHoc = new javax.swing.JMenuItem();
        miHocVien = new javax.swing.JMenuItem();
        miNguoiHoc = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miNhanVien = new javax.swing.JMenuItem();
        mThongKe = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        mGiupDo = new javax.swing.JMenu();
        miHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblTime.setForeground(new java.awt.Color(255, 0, 0));
        lblTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clock.png"))); // NOI18N
        lblTime.setText("Đồng hồ nè");

        lblInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Info.png"))); // NOI18N
        lblInfo.setText("Nhân viên: abc Vai trò xyz");

        jToolBar1.setRollover(true);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Log out.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogout);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Exit.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lists.png"))); // NOI18N
        btnChuyenDe.setText("Chuyên đề");
        btnChuyenDe.setFocusable(false);
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChuyenDe);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Certificate.png"))); // NOI18N
        jButton1.setText("Khóa học");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clien list.png"))); // NOI18N
        jButton2.setText("Người học");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        btnGuide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Globe.png"))); // NOI18N
        btnGuide.setText("Giới thiệu");
        btnGuide.setFocusable(false);
        btnGuide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuide.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuideActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuide);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo.png"))); // NOI18N

        mHeThong.setText("Hệ thống");

        miChangPass.setText("Đổi mật khẩu");
        miChangPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miChangPassActionPerformed(evt);
            }
        });
        mHeThong.add(miChangPass);

        miLogout.setText("Đăng xuất");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mHeThong.add(miLogout);

        miExit.setText("Thoát");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mHeThong.add(miExit);

        mbEduSYS.add(mHeThong);

        mQuanLy.setText("Quản lý");

        miChuyenDe.setText("Chuyên đề");
        miChuyenDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miChuyenDeMouseClicked(evt);
            }
        });
        miChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miChuyenDeActionPerformed(evt);
            }
        });
        mQuanLy.add(miChuyenDe);

        miKhoaHoc.setText("Khóa học");
        miKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKhoaHocActionPerformed(evt);
            }
        });
        mQuanLy.add(miKhoaHoc);

        miHocVien.setText("Học viên");
        miHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHocVienActionPerformed(evt);
            }
        });
        mQuanLy.add(miHocVien);

        miNguoiHoc.setText("Người học");
        miNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNguoiHocActionPerformed(evt);
            }
        });
        mQuanLy.add(miNguoiHoc);
        mQuanLy.add(jSeparator2);

        miNhanVien.setText("Nhân viên");
        miNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNhanVienActionPerformed(evt);
            }
        });
        mQuanLy.add(miNhanVien);

        mbEduSYS.add(mQuanLy);

        mThongKe.setText("Thống kê");

        jMenuItem6.setText("jMenuItem6");
        mThongKe.add(jMenuItem6);
        mThongKe.add(jSeparator3);

        jMenuItem7.setText("jMenuItem7");
        mThongKe.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        mThongKe.add(jMenuItem8);

        jMenuItem9.setText("jMenuItem9");
        mThongKe.add(jMenuItem9);

        mbEduSYS.add(mThongKe);

        mGiupDo.setText("Giúp đỡ");

        miHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/facebook.png"))); // NOI18N
        miHelp.setText("Không biết giúp gì luôn á?");
        miHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miHelpMouseClicked(evt);
            }
        });
        miHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHelpActionPerformed(evt);
            }
        });
        mGiupDo.add(miHelp);

        mbEduSYS.add(mGiupDo);

        setJMenuBar(mbEduSYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                        .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(lblInfo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miChangPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miChangPassActionPerformed
        // TODO add your handling code here:
        openChangePassword();
    }//GEN-LAST:event_miChangPassActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        logOut();
    }//GEN-LAST:event_miLogoutActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_miExitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        logOut();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuideActionPerformed
        // TODO add your handling code here:
        openAbout();
    }//GEN-LAST:event_btnGuideActionPerformed

    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed
        // TODO add your handling code here:
        openChuyenDe();
    }//GEN-LAST:event_btnChuyenDeActionPerformed

    private void miChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miChuyenDeActionPerformed
        // TODO add your handling code here:
        openChuyenDe();
    }//GEN-LAST:event_miChuyenDeActionPerformed

    private void miHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miHelpMouseClicked
        // TODO add your handling code here:
        openGuide();
    }//GEN-LAST:event_miHelpMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        openKhoaHoc();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        openNguoiHoc();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void miChuyenDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miChuyenDeMouseClicked
        // TODO add your handling code here:
        openChuyenDe();
    }//GEN-LAST:event_miChuyenDeMouseClicked

    private void miKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKhoaHocActionPerformed
        // TODO add your handling code here:
        openKhoaHoc();
    }//GEN-LAST:event_miKhoaHocActionPerformed

    private void miHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHocVienActionPerformed
        // TODO add your handling code here:
        openHocVien();
    }//GEN-LAST:event_miHocVienActionPerformed

    private void miNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNguoiHocActionPerformed
        // TODO add your handling code here:
        openNguoiHoc();
    }//GEN-LAST:event_miNguoiHocActionPerformed

    private void miNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNhanVienActionPerformed
        // TODO add your handling code here:
        openNhanVien();
    }//GEN-LAST:event_miNhanVienActionPerformed

    private void miHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHelpActionPerformed
        // TODO add your handling code here:
        openGuide();
    }//GEN-LAST:event_miHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuide;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblTime;
    private javax.swing.JMenu mGiupDo;
    private javax.swing.JMenu mHeThong;
    private javax.swing.JMenu mQuanLy;
    private javax.swing.JMenu mThongKe;
    private javax.swing.JMenuBar mbEduSYS;
    private javax.swing.JMenuItem miChangPass;
    private javax.swing.JMenuItem miChuyenDe;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miHelp;
    private javax.swing.JMenuItem miHocVien;
    private javax.swing.JMenuItem miKhoaHoc;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miNguoiHoc;
    private javax.swing.JMenuItem miNhanVien;
    // End of variables declaration//GEN-END:variables
}
